### PR TITLE
Feature // Storage Meter in Account Popover // 106203132

### PR DESCRIPTION
**Pull request by tomnez**
[Pivotal Story 106203132](https://www.pivotaltracker.com/story/show/106203132)

Behold, my firstest PR into the style guide.

This PR implements the storage meter into the account-popover.

Mocks:
account_storage_popover_set_v5-1

### CODE REVIEW

**Comment by nmcclay** [comment]
Could you add a sample of your 'progress-thin' component to the progress bar sample partial?

**Comment by tomnez** [comment]
@nmcclay yeassum, updated.

**Comment by nmcclay** [comment]
So this looks good from a practical standpoint of the component and the css.  I have a usage concern though, without a mechanism to reliably set the storage capacity state UI from the client perspective we will likely have very inconsistent behavior across the forever apps that integrate this component.

A suggested fix would be making a component script that allows us to 'set' the storage capacity and dynamically apply the correct state to the progress bar.  Considering this PR is from our premiere javascript ninja, what do you think @tomnez ?

**Comment by tomnez** [comment]
I was thinking about that too. With the web app, we can't just import the modules from the style guide, we currently have to copy/paste the template since we can't use `render partial`, so we're going to have to edit the markup already with or without a script which is why I kind of left it up in the air.

Do the store and marketing site have a `user` loaded with the storage data available? It would be nice if we could just put `<%= user.membership_type %>` etc. in the style guide and have it work in both the store and marketing site, rather than populate it with javascript.

If not, then I'd say yes to a script, but then we'd also have to make sure there's a way to get all the storage/membership data in all the apps.

**Comment by nmcclay** [comment]
Could you add some comments for usage of this javascript?  Its nice javascript, but some documentation would be really useful.

**Comment by tomnez** [comment]
@nmcclay I has updated with commentings.

**Comment by nmcclay** [comment]
I like it!  I WANT IT INSIDE STYLE GUIDE!

**Comment by nmcclay** [comment]
oops I pressed the wrong button...

**Comment by tomnez** [comment]
ace-dance

**Pull request merged**
