### PR TITLE
add panstoria trademark

### PR DESCRIPTION
**Pull request by amiballo**
Add the Panstoria trademark method
https://www.pivotaltracker.com/n/projects/1516202/stories/152803637

### CODE REVIEW

**Comment by amiballo** [comment]
@alexisBimatovs I would like to add the <^%= trademark('Forever', 'trademark') %> method since it currently does not exist, but wondering if it's acceptable to add that into this PR

**Comment by alexisBimatovs** [comment]
we are currently on 3.2.16 can you do a version bump for this and I will get it merged?

screen shot 2017-12-07 at 2 50 43 pm

**Comment by alexisBimatovs** [comment]
@amiballo back to you

**Comment by amiballo** [comment]
@alexisBimatovs version bumped up! Back to you

**Pull request merged**
