### PR TITLE
Navigation updates for marketing website

### PR DESCRIPTION
**Pull request by nmcclay**
also a readme fix

### CODE REVIEW

**Comment by schweitzdesign** [comment]
Text underline on hover state doesn't look intentional.

screen shot 2015-08-13 at 3 55 58 pm

**Comment by nmcclay** [comment]
oops, yeah totally fixing that now haha

**Comment by schweitzdesign** [comment]
Pretty minor stuff here. Seeing that menu expanded in my actual browser window is very nice looking.

**Comment by nmcclay** [comment]
ok should be good to go now,

**Comment by schweitzdesign** [comment]
Just two things:
1- There's a merge conflict that needs resolved here.
2 - What do you think about only highlighting .dropdown-menu-product-title on hover & not the whole text block?

screen shot 2015-08-14 at 1 25 28 pm

**Comment by schweitzdesign** [comment]
Looks good!

**Pull request merged**
