### PR TITLE
Feature/performance imporovements and major version bump

### PR DESCRIPTION
**Pull request by schweitzdesign**
* Removes Compass
* Only imports Bootstrap CSS modules we're actually using
* Removes redundant JS (we were loading all of Bootstrap twice!)

### CODE REVIEW

**Comment by tomnez** [comment]
@schweitzdesign conflicts! :ghost:

**Comment by schweitzdesign** [comment]
@tomnez green!

**Comment by tomnez** [comment]
aw man

**Comment by tomnez** [comment]
Asset error!

screen shot 2016-03-10 at 10 41 54 am

**Comment by schweitzdesign** [comment]
@tomnez updated.

**Comment by tomnez** [comment]
@schweitzdesign the code looks ok, the only problem I found was with the button groups, I think some of the updated styles might be missing/wrong:

#### Old Hotness:
screen shot 2016-03-15 at 3 48 36 pm

#### New Bustedness:
screen shot 2016-03-15 at 3 49 55 pm

After fixing that we can finally merge this, biaaatch.

**Comment by schweitzdesign** [comment]
Updated @tomnez.

**Comment by tomnez** [comment]
Hooray!

**Pull request merged**
