### PR TITLE
markup and style new footer component

### PR DESCRIPTION
**Pull request by schweitzdesign**
Pivotal: https://www.pivotaltracker.com/story/show/100764732

large

medium

small

### CODE REVIEW

**Comment by csto** [comment]
I have a concern with the "Sign in" and "Join Today" buttons conflicting with the last section of each marketing product page, since they will contain similar CTA's.

I also have a larger concern with the Ambassador Sign in and Sign up links.  I think these links provide little benefit at the risk of confusion with real sign up links and accidental sign up.

**Comment by nmcclay** [comment]
If we do use a fixed header then I think that the benefit here is definitely negligible for additional sign up/in CTAs at the bottom.  However If you do look at a stellar conversion flow like https://www.getflow.com/ they definitely don't have a problem with duplicating their primary sign up.  

The ambassador point I think is definitely true that an entirely different sign up workflow is potentially confusing.  I think just having a link to the ambassador home page would be preferable.

**Comment by schweitzdesign** [comment]
I updated the ambassador links. I do think I'm ultimately in favor of the redundant sign in / join today buttons in the footer. There's value in signing up from anywhere in the site to start your forever web app experience or gain access to launching print products online and in the case of Artisan and Historian, I think the bottom section CTAs are distinct enough to not be confusing.

screen shot 2015-08-26 at 8 54 27 am

**Comment by schweitzdesign** [comment]
Refined the background color and overall contrast a bit: 
screen shot 2015-08-26 at 11 05 44 am

**Comment by nmcclay** [comment]
Is there a reason this footer uses a separate image from the one we use in the dropdown?  Shouldn't we reference the same image so when we update one it updates the other?

**Comment by schweitzdesign** [comment]
The main reason to use different images here was that the footer requires these images to all be rendered at the same width so you don't get scaling issues in responsive contexts. 

I agree that referencing the same image would be handy, but presuming that these will change only very infrequently I don't think it's a total necessity.

However, taking a closer look, it seems like there is also a scaling issue at a mid breakpoint w/ the images as used in the header, so I'm thinking we should use the same images in both contexts, but those images should be rendered at a consistent width.

screen shot 2015-09-02 at 10 12 30 am
screen shot 2015-09-02 at 10 12 11 am

**Comment by nmcclay** [comment]
I would be fine with that, do you want to update these graphics from the illustrator file and push that in with this PR?  historian logo needs updated anyways.

**Comment by schweitzdesign** [comment]
Images updated @nmcclay.

**Pull request merged**
