### PR TITLE
Dev - release 1.2.10!

### PR DESCRIPTION
**Pull request by nmcclay**

### CODE REVIEW

**Comment by nmcclay** [comment]
@schweitzdesign I noticed an odd hero/navbar margin issue that I think was introduced in 1.2.8, but I wanted to look at with you before proceeding to merge to master.

**Comment by schweitzdesign** [comment]
The default bootstrap .navbar has margin-bottom: 20px; We overwrite this in _nav-fixed.scss so that's why it's only seen in the styleguide nav.

**Comment by nmcclay** [comment]
Got it, I think this is fine just wanted to double check.

**Comment by schweitzdesign** [comment]
Was this released as a version on ruby gems as well?

**Comment by nmcclay** [comment]
yep: https://rubygems.org/gems/forever_style_guide/versions/1.2.10

**Comment by schweitzdesign** [comment]
great!

**Pull request merged**
