### PR TITLE
Feature/add live 18 colors/noticket

### PR DESCRIPTION
**Pull request by amiballo**
Add Forever Live 18! colors to style guide 
screen shot 2017-10-30 at 4 37 06 pm

### CODE REVIEW

**Comment by alexisBimatovs** [comment]
@amiballo to note I just published 3.2.14 so this will need to bump again :)

**Comment by alexisBimatovs** [comment]
@amiballo can you reserve conflicts and I will review this

**Comment by amiballo** [comment]
@alexisBimatovs conflicts resolved!

**Comment by alexisBimatovs** [comment]
pulling in the store works great hehe

screen shot 2017-11-01 at 2 44 54 pm
screen shot 2017-11-01 at 3 08 45 pm

**Comment by alexisBimatovs** [comment]
other than your spelling on GRAY LGTM lol

**Pull request merged**
