### PR TITLE
Updated signed in nav example

### PR DESCRIPTION
**Pull request by nmcclay**

### CODE REVIEW

**Comment by nmcclay** [comment]
The markup in  app/views/forever_style_guide/sections/components/navigation/_signed_in.erb will get you started Tomnez, I'm fixing some breakpoint display weirdness for the account avatar.

**Comment by nmcclay** [comment]
Should be good to go now

**Comment by schweitzdesign** [comment]
We talked yesterday about the left hand options here being different so as to be more relevant to the in-app experience (ex. "Buy Permanent Storage, Forever Artisan, Services, etc). 

I think the consistency is fine, but just wanted to double check.

screen shot 2015-09-23 at 8 39 48 am

**Comment by schweitzdesign** [comment]
Once the toggle is exposed there's some max-height and overflow weirdness going on.

screen shot 2015-09-23 at 8 48 25 am
screen shot 2015-09-23 at 8 48 34 am
screen shot 2015-09-23 at 8 48 48 am

**Comment by nmcclay** [comment]
Oops looks like some breakpoint weirdness, good catch!  I hadn't updated the more menu items yet.  I can definitely do that.  Good feedback overall!

**Comment by schweitzdesign** [comment]
One small issue w/ the padding on mobile. The account-popover div is missing an l-padded-thin class and there's a padding: 0, that would be overriding it anyway.

screen shot 2015-09-23 at 1 17 53 pm

**Comment by schweitzdesign** [comment]
Looks good!

**Pull request merged**
